# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- feature/FrameworkModifications

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'apitests/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: 'apitests/target/karate-reports/karate-summary.html'
    goals: 'test -Dtest=ParallelExecutionTest -Dkarate.env=test'
    
# - task: PublishTestResults@2
#   displayName: 'Publish Test Results'
#   inputs:
#     testResultsFiles: '*.xml'
#     searchFolder: '$(System.DefaultWorkingDirectory)/apitests/target/surefire-reports'
#     mergeTestResults: true
#     testRunTitle: 'Platform Api testing'
#   continueOnError: true
#   condition: succeededOrFailed()
  
- task: PublishPipelineArtifact@1
  displayName: 'Publish Karate Reports'
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/apitests/target/karate-reports
    artifact: 'Karate reports'
  condition: succeededOrFailed()
  
  
# - task: PublishPipelineArtifact@1
#   displayName: 'Publish Surefire Reports'
#   inputs:
#     targetPath: $(System.DefaultWorkingDirectory)/apitests/target/surefire-reports
#     artifact: 'SureFire Junit reports'
#   condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  displayName: 'Publish Cucumber Reports'
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/apitests/target/cucumber-html-reports
    artifact: 'Cucumber reports'
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish MembershipSbe Results'
  inputs:
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/apitests/target/karate-reports'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Membership SBE Tests'
  continueOnError: true
  condition: succeededOrFailed()

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceNameARM'
    azureServiceConnection: 'GDAY GROUP Enterprise Dev/Test (ff650bb8-3ff4-4fd1-865c-829ed593b384)'
    method: 'POST'
    headers: |
      {
      "Content-Type":"application/json", 
      "PlanUrl": "$(system.CollectionUri)", 
      "ProjectId": "$(system.TeamProjectId)", 
      "HubName": "$(system.HostType)", 
      "PlanId": "$(system.PlanId)", 
      "JobId": "$(system.JobId)", 
      "TimelineId": "$(system.TimelineId)", 
      }
    body: |
      {
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "Test Robot",
          "sections": [
              {
                  "activityTitle": "Test Robot ran the Karate API Tests in Test",
                  "activitySubtitle": "Customer Web Test",
                  "activityImage": "https://i.imgur.com/S9NXAEz.png",
                  "facts": [
                      {
                          "name": "Assigned to",
                          "value": "RJ"
                      }
                  ],
                  "markdown": true
              }
          ],
          "potentialAction": [
              {
                  "@type": "OpenUri",
                  "name": "Test Results",
                  "targets": [
                      {
                          "os": "default",
                          "uri": "https://discoveryparks.visualstudio.com/Test%20Automation/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab"
                      }
                  ]
              }
          ]
      }
    urlSuffix: 'https://discoveryholidayparks.webhook.office.com/webhookb2/62eee273-9e9f-4336-940f-636caf8f8053@1400c903-3a54-41dd-a597-241ce11262da/IncomingWebhook/ebc51e82c37248b89a76ec1cbaf5094c/777ca911-ba2b-47d6-af57-072c05c79eb1'
    waitForCompletion: 'false'
  condition: Failed()